version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: php-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - lamp-network
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    networks:
      - lamp-network
    ports:
      - "8081:3306"

volumes:
  db-data:

networks:
  lamp-network:
